# Generated by Django 5.1.5 on 2025-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='people_booked',
            field=models.IntegerField(default=0),
        ),
    ]
