# Generated by Django 5.1.5 on 2025-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_availability_status_room_people_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='availability_status',
            new_name='availability_status_moodIndigo',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='people_booked',
            new_name='people_booked_moodIndigo',
        ),
        migrations.AddField(
            model_name='room',
            name='availability_status_techFest',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='people_booked_techFest',
            field=models.IntegerField(default=0),
        ),
    ]
