# Generated by Django 5.1.5 on 2025-02-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_hostel_hostel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='price_per_booking',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
