# Generated by Django 5.1.5 on 2025-01-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_room_per_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.CharField(choices=[('Mood Indigo', 'Mood Indigo'), ('Techfest', 'Techfest')], default='Mood Indigo', max_length=20),
        ),
    ]
