# Generated by Django 5.1.5 on 2025-01-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_unique_booking_per_room_per_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
