# Generated by Django 5.1.5 on 2025-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_end_date_remove_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2024-12-27'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2024-12-24'),
        ),
    ]
