# Generated by Django 5.1.5 on 2025-01-27 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_end_date_remove_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resident_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the person staying in the room', max_length=100),
            preserve_default=False,
        ),
    ]
